service: practice-nodejs-typescript

provider:
  name: aws
  runtime: nodejs12.x
  apiName: typescript-api
  region: ap-northeast-2

plugins:
  - serverless-plugin-typescript

functions:
  hello:
    handler: handler.hello
    name: typescript
    events:
      - http:
          path: hello/{proxy+}
          method: get