service: practice-serverless-lambda

provider:
  name: aws
  runtime: nodejs12.x
  apiName: express-api
  region: ap-northeast-2

functions:
  api:
    handler: handler.api
    name: express
    events:
      - http:
          path: /
          method: get
          cors: true
      - http:
          path: /pow
          method: get
          cors: true