service: src

provider:
  name: aws
  runtime: nodejs12.x
  apiName: helloworld-api
  region: ap-northeast-2

functions:
  helloWorld:
    handler: handler.helloWorld
    name: helloworld
    events:
      - http:
          path: hello-world
          method: get
          cors: true
